### ISSUE TITLE
[meta] PV modelling plan

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-prediction#1]
# Problem
Idea is to do some PV forecasting on a site level. 
We want to start simple and build up on a model level but also on a data level. 

Start with ~ 4 hours forecasts

Public data
[PV](https://huggingface.co/datasets/openclimatefix/uk_pv)

# Data
ocf_datapipes is a pipeline for getting lots of data sources together. They include PV, NWP, Satellite data sources as whereas as some other features like sun elevation

# Task lists
- [ ] Understand [ocf_datapipes](https://github.com/openclimatefix/ocf_datapipes)
- [x] Make sure data is on GCP
- [x] Setup GCP machine, @peterdudfield to help
- [x] https://github.com/openclimatefix/PVSBRI/issues/2
- [x] https://github.com/openclimatefix/PVSBRI/issues/3
- [x] Run XGBooast model on pv+nwp
- [ ] Run XGBooast model on pv+nwp + satellite
- [ ] Run 4 FC model on pv+nwp + satellite
- [ ] Run PVnet model on pv+nwp + satellite
- [ ] Run `Transformer` model on pv+nwp + satellite
- [ ] Setup repo with hydra to run experiments
- [x] 36 hours modelling
- [ ] Setup up wandb
- [x] Run inference

# Production
- [ ] save model to HF
- [x] either use nowcasting_forecast, or perhaps set up serrate repo to load model
- [ ] Nie module format, so it can easily by upgraded to use new model
- [ ] run inference for all sites
- [ ] save to db (db models might be made by then)

Some inspriation 
- https://github.com/openclimatefix/PVItaly and https://github.com/openclimatefix/PV-Challenge
