### ISSUE TITLE
Set units to `kw`

### ISSUE THREAD

**Issue by simlmx** [openclimatefix/pv-site-prediction#29]
# Description
So far we have used the `Wh/5min` units for power. We should simplify and use `kW` everywhere, so that we know what to expect once in prod.

# TODOs
- [x] Make the scripts that parse the data `kw`-friendly (add an option to convert to `kW`)
- [x] Fix the dataset to be in `kW`
- [x] Fix the inferred metadata to be in `kW`
- [x] Make sure the script is clear as to what it does with units
- [x] Train a model in `kW`
- [x] Evaluate it and do sample analysis to make sure everything seems fine
- [x] Double check that we don't do funny conversions anywhere
- [x] Put that model in the dev environment in AWS
- [x] Update the code of `pv-site-production` to remove unit conversions and use the new model

**Comment by simlmx** [comment]
All fixed!
